name: Build VSIX

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
permissions:
  id-token: write # This is required for the federated credential to work
  
env:
  VERSION: 3.1.${{ github.run_number }}
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore Packages
      run: nuget restore SSMSExecutor.sln

    - name: Build Solution
      run: msbuild.exe SSMSExecutor.sln /property:Configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
    
    - name: Move build output
      if: github.ref == 'refs/heads/master' && github.repository_owner == 'tkwj' && (github.event_name == 'push' ||  github.event_name == 'workflow_dispatch')
      run: |
        mv SSMSExecutor/bin/Release/SSMSExecutor.vsix SSMSExecutor-${{ env.VERSION }}.vsix
        
    - name: Azure CLI login with federated credential
      if: github.event_name != 'pull_request'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Run az commands
      run: |
        az account show
        az group list
          
    - name: Install dotnet sign
      if: github.event_name != 'pull_request'
      run: dotnet tool install --global sign --prerelease

    - name: Sign VSIX packages
      if: github.ref == 'refs/heads/master' && github.repository_owner == 'tkwj' && (github.event_name == 'push' ||  github.event_name == 'workflow_dispatch')
      run: sign code trusted-signing *.vsix SSMSExecutor/bin/Release/SSMSExecutor.dll `
        --trusted-signing-account tkwj `
        --trusted-signing-certificate-profile tkwj-github `
        --trusted-signing-endpoint https://eus.codesigning.azure.net `
        --verbosity information

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 3.1.${{ github.run_number }}.zip
        path: 'SSMSExecutor/bin/Release/'
        exclusions: '*.vsix'
        custom: '-j'

    - name: Publish artifacts
      if: github.ref == 'refs/heads/master' && github.repository_owner == 'tkwj' && (github.event_name == 'push' ||  github.event_name == 'workflow_dispatch')
      uses: actions/upload-artifact@v5
      with:
        name: Artifacts
        path: |
          *.vsix
          *.zip
